# Generated by Django 4.0.5 on 2022-06-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_react_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='file',
        ),
    ]
