# Generated by Django 4.0.5 on 2022-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_react_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
