# Generated by Django 4.0.4 on 2022-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_excelfile_sftp_delete_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sftp',
            name='host_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sftp',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sftp',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sftp',
            name='upload_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sftp',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
